-- THIS FILE WAS AUTOMATICALLY GENERATED. DO NOT EDIT BY HAND --

local M = {}
M.Elems = {
--{ Name        , Type  ,  },
  { 'a'         , 'Flow',  },
  { 'abbr'      , 'Flow',  },
  { 'address'   , 'Flow',  },
  { 'area'      , 'Void',  },
  { 'article'   , 'Flow',  },
  { 'aside'     , 'Flow',  },
  { 'audio'     , 'Flow',  },
  { 'b'         , 'Flow',  },
  { 'base'      , 'Void',  },
  { 'bdi'       , 'Flow',  },
  { 'bdo'       , 'Flow',  },
  { 'blockquote', 'Flow',  },
  { 'body'      , 'Flow',  },
  { 'br'        , 'Void',  },
  { 'button'    , 'Flow',  },
  { 'canvas'    , 'Flow',  },
  { 'caption'   , 'Flow',  },
  { 'cite'      , 'Flow',  },
  { 'code'      , 'Flow',  },
  { 'col'       , 'Void',  },
  { 'colgroup'  , 'Flow',  },
  { 'data'      , 'Flow',  },
  { 'datalist'  , 'Flow',  },
  { 'dd'        , 'Flow',  },
  { 'del'       , 'Flow',  },
  { 'details'   , 'Flow',  },
  { 'dfn'       , 'Flow',  },
  { 'dialog'    , 'Flow',  },
  { 'div'       , 'Flow',  },
  { 'dl'        , 'Flow',  },
  { 'dt'        , 'Flow',  },
  { 'em'        , 'Flow',  },
  { 'embed'     , 'Void',  },
  { 'fieldset'  , 'Flow',  },
  { 'figcaption', 'Flow',  },
  { 'figure'    , 'Flow',  },
  { 'footer'    , 'Flow',  },
  { 'form'      , 'Flow',  },
  { 'h1'        , 'Flow',  },
  { 'head'      , 'Flow',  },
  { 'header'    , 'Flow',  },
  { 'hgroup'    , 'Flow',  },
  { 'hr'        , 'Void',  },
  { 'html'      , 'Flow',  },
  { 'i'         , 'Flow',  },
  { 'iframe'    , 'Flow',  },
  { 'img'       , 'Void',  },
  { 'input'     , 'Void',  },
  { 'ins'       , 'Flow',  },
  { 'kbd'       , 'Flow',  },
  { 'keygen'    , 'Void',  },
  { 'label'     , 'Flow',  },
  { 'legend'    , 'Flow',  },
  { 'li'        , 'Flow',  },
  { 'link'      , 'Void',  },
  { 'main'      , 'Flow',  },
  { 'map'       , 'Flow',  },
  { 'mark'      , 'Flow',  },
  { 'menu'      , 'Flow',  },
  { 'menuitem'  , 'Void',  },
  { 'meta'      , 'Void',  },
  { 'meter'     , 'Flow',  },
  { 'nav'       , 'Flow',  },
  { 'noscript'  , 'Flow',  },
  { 'object'    , 'Flow',  },
  { 'ol'        , 'Flow',  },
  { 'optgroup'  , 'Flow',  },
  { 'option'    , 'Flow',  },
  { 'output'    , 'Flow',  },
  { 'p'         , 'Flow',  },
  { 'param'     , 'Void',  },
  { 'pre'       , 'Flow',  },
  { 'progress'  , 'Flow',  },
  { 'q'         , 'Flow',  },
  { 'rp'        , 'Flow',  },
  { 'rt'        , 'Flow',  },
  { 'ruby'      , 'Flow',  },
  { 's'         , 'Flow',  },
  { 'samp'      , 'Flow',  },
  { 'script'    , 'Raw' ,  },
  { 'section'   , 'Flow',  },
  { 'select'    , 'Flow',  },
  { 'small'     , 'Flow',  },
  { 'source'    , 'Void',  },
  { 'span'      , 'Flow',  },
  { 'strong'    , 'Flow',  },
  { 'style'     , 'Raw' ,  },
  { 'sub'       , 'Flow',  },
  { 'summary'   , 'Flow',  },
  { 'sup'       , 'Flow',  },
  { 'table'     , 'Flow',  },
  { 'tbody'     , 'Flow',  },
  { 'td'        , 'Flow',  },
  { 'template'  , 'Flow',  },
  { 'textarea'  , 'Flow',  },
  { 'tfoot'     , 'Flow',  },
  { 'th'        , 'Flow',  },
  { 'thead'     , 'Flow',  },
  { 'time'      , 'Flow',  },
  { 'title'     , 'Flow',  },
  { 'tr'        , 'Flow',  },
  { 'track'     , 'Void',  },
  { 'u'         , 'Flow',  },
  { 'ul'        , 'Flow',  },
  { 'var'       , 'Flow',  },
  { 'video'     , 'Flow',  },
  { 'wbr'       , 'Void',  },
}
M.Attrs = {
--{ Name              , Type     , Allowed Elements                                                                                                               ,  },
  { 'abbr'            , 'Text'   , { 'th' }                                                                                                                       ,  },
  { 'accept'          , 'Text'   , { 'input' }                                                                                                                    ,  },
  { 'accept-charset'  , 'Text'   , { 'form' }                                                                                                                     ,  },
  { 'accesskey'       , 'Text'   , true                                                                                                                           ,  },
  { 'action'          , 'URL'    , { 'form' }                                                                                                                     ,  },
  { 'allowfullscreen' , 'Boolean', { 'iframe' }                                                                                                                   ,  },
  { 'alt'             , 'Text'   , { 'area', 'img', 'input' }                                                                                                     ,  },
  { 'async'           , 'Boolean', { 'script' }                                                                                                                   ,  },
  { 'autocomplete'    , 'Text'   , { 'form', 'input', 'select', 'textarea' }                                                                                      ,  },
  { 'autofocus'       , 'Boolean', { 'button', 'input', 'keygen', 'select', 'textarea' }                                                                          ,  },
  { 'autoplay'        , 'Boolean', { 'audio', 'video' }                                                                                                           ,  },
  { 'challenge'       , 'Text'   , { 'keygen' }                                                                                                                   ,  },
  { 'charset'         , 'Text'   , { 'meta', 'script' }                                                                                                           ,  },
  { 'checked'         , 'Boolean', { 'menuitem', 'input' }                                                                                                        ,  },
  { 'cite'            , 'URL'    , { 'blockquote', 'del', 'ins', 'q' }                                                                                            ,  },
  { 'class'           , 'Text'   , true                                                                                                                           ,  },
  { 'cols'            , 'Text'   , { 'textarea' }                                                                                                                 ,  },
  { 'colspan'         , 'Text'   , { 'td', 'th' }                                                                                                                 ,  },
  { 'command'         , 'Text'   , { 'menuitem' }                                                                                                                 ,  },
  { 'content'         , 'Text'   , { 'meta' }                                                                                                                     ,  },
  { 'contenteditable' , 'Text'   , true                                                                                                                           ,  },
  { 'contextmenu'     , 'Text'   , true                                                                                                                           ,  },
  { 'controls'        , 'Boolean', { 'audio', 'video' }                                                                                                           ,  },
  { 'coords'          , 'Text'   , { 'area' }                                                                                                                     ,  },
  { 'crossorigin'     , 'Text'   , { 'audio', 'img', 'link', 'script', 'video' }                                                                                  ,  },
  { 'data'            , 'URL'    , { 'object' }                                                                                                                   ,  },
  { 'datetime'        , 'Text'   , { 'del', 'ins', 'time' }                                                                                                       ,  },
  { 'default'         , 'Boolean', { 'menuitem', 'track' }                                                                                                        ,  },
  { 'defer'           , 'Boolean', { 'script' }                                                                                                                   ,  },
  { 'dir'             , 'Text'   , true                                                                                                                           ,  },
  { 'dirname'         , 'Text'   , { 'input', 'textarea' }                                                                                                        ,  },
  { 'disabled'        , 'Boolean', { 'button', 'menuitem', 'fieldset', 'input', 'keygen', 'optgroup', 'option', 'select', 'textarea' }                            ,  },
  { 'download'        , 'Text'   , { 'a', 'area' }                                                                                                                ,  },
  { 'draggable'       , 'Text'   , true                                                                                                                           ,  },
  { 'dropzone'        , 'Text'   , true                                                                                                                           ,  },
  { 'enctype'         , 'Text'   , { 'form' }                                                                                                                     ,  },
  { 'for'             , 'Text'   , { 'label', 'output' }                                                                                                          ,  },
  { 'form'            , 'Text'   , { 'button', 'fieldset', 'input', 'keygen', 'label', 'object', 'output', 'select', 'textarea' }                                 ,  },
  { 'formaction'      , 'URL'    , { 'button', 'input' }                                                                                                          ,  },
  { 'formenctype'     , 'Text'   , { 'button', 'input' }                                                                                                          ,  },
  { 'formmethod'      , 'Text'   , { 'button', 'input' }                                                                                                          ,  },
  { 'formnovalidate'  , 'Boolean', { 'button', 'input' }                                                                                                          ,  },
  { 'formtarget'      , 'Text'   , { 'button', 'input' }                                                                                                          ,  },
  { 'headers'         , 'Text'   , { 'td', 'th' }                                                                                                                 ,  },
  { 'height'          , 'Text'   , { 'canvas', 'embed', 'iframe', 'img', 'input', 'object', 'video' }                                                             ,  },
  { 'hidden'          , 'Boolean', true                                                                                                                           ,  },
  { 'high'            , 'Text'   , { 'meter' }                                                                                                                    ,  },
  { 'href'            , 'URL'    , { 'a', 'area', 'link', 'base' }                                                                                                ,  },
  { 'hreflang'        , 'Text'   , { 'a', 'area', 'link' }                                                                                                        ,  },
  { 'http-equiv'      , 'Text'   , { 'meta' }                                                                                                                     ,  },
  { 'icon'            , 'URL'    , { 'menuitem' }                                                                                                                 ,  },
  { 'id'              , 'Text'   , true                                                                                                                           ,  },
  { 'inert'           , 'Boolean', true                                                                                                                           ,  },
  { 'inputmode'       , 'Text'   , { 'input', 'textarea' }                                                                                                        ,  },
  { 'ismap'           , 'Boolean', { 'img' }                                                                                                                      ,  },
  { 'itemid'          , 'URL'    , true                                                                                                                           ,  },
  { 'itemprop'        , 'Text'   , true                                                                                                                           ,  },
  { 'itemref'         , 'Text'   , true                                                                                                                           ,  },
  { 'itemscope'       , 'Boolean', true                                                                                                                           ,  },
  { 'itemtype'        , 'Text'   , true                                                                                                                           ,  },
  { 'keytype'         , 'Text'   , { 'keygen' }                                                                                                                   ,  },
  { 'kind'            , 'Text'   , { 'track' }                                                                                                                    ,  },
  { 'label'           , 'Text'   , { 'menuitem', 'menu', 'optgroup', 'option', 'track' }                                                                          ,  },
  { 'lang'            , 'Text'   , true                                                                                                                           ,  },
  { 'list'            , 'Text'   , { 'input' }                                                                                                                    ,  },
  { 'loop'            , 'Boolean', { 'audio', 'video' }                                                                                                           ,  },
  { 'low'             , 'Text'   , { 'meter' }                                                                                                                    ,  },
  { 'manifest'        , 'URL'    , { 'html' }                                                                                                                     ,  },
  { 'max'             , 'Text'   , { 'input', 'meter', 'progress' }                                                                                               ,  },
  { 'maxlength'       , 'Text'   , { 'input', 'textarea' }                                                                                                        ,  },
  { 'media'           , 'Text'   , { 'link', 'source', 'style' }                                                                                                  ,  },
  { 'mediagroup'      , 'Text'   , { 'audio', 'video' }                                                                                                           ,  },
  { 'menu'            , 'Text'   , { 'button' }                                                                                                                   ,  },
  { 'method'          , 'Text'   , { 'form' }                                                                                                                     ,  },
  { 'min'             , 'Text'   , { 'input', 'meter' }                                                                                                           ,  },
  { 'minlength'       , 'Text'   , { 'input', 'textarea' }                                                                                                        ,  },
  { 'multiple'        , 'Boolean', { 'input', 'select' }                                                                                                          ,  },
  { 'muted'           , 'Boolean', { 'audio', 'video' }                                                                                                           ,  },
  { 'name'            , 'Text'   , { 'button', 'fieldset', 'input', 'keygen', 'output', 'select', 'textarea', 'form', 'iframe', 'object', 'map', 'meta', 'param' },  },
  { 'novalidate'      , 'Boolean', { 'form' }                                                                                                                     ,  },
  { 'open'            , 'Boolean', { 'details', 'dialog' }                                                                                                        ,  },
  { 'optimum'         , 'Text'   , { 'meter' }                                                                                                                    ,  },
  { 'pattern'         , 'Text'   , { 'input' }                                                                                                                    ,  },
  { 'ping'            , 'Text'   , { 'a', 'area' }                                                                                                                ,  },
  { 'placeholder'     , 'Text'   , { 'input', 'textarea' }                                                                                                        ,  },
  { 'poster'          , 'URL'    , { 'video' }                                                                                                                    ,  },
  { 'preload'         , 'Text'   , { 'audio', 'video' }                                                                                                           ,  },
  { 'radiogroup'      , 'Text'   , { 'menuitem' }                                                                                                                 ,  },
  { 'readonly'        , 'Boolean', { 'input', 'textarea' }                                                                                                        ,  },
  { 'rel'             , 'Text'   , { 'a', 'area', 'link' }                                                                                                        ,  },
  { 'required'        , 'Boolean', { 'input', 'select', 'textarea' }                                                                                              ,  },
  { 'reversed'        , 'Boolean', { 'ol' }                                                                                                                       ,  },
  { 'rows'            , 'Text'   , { 'textarea' }                                                                                                                 ,  },
  { 'rowspan'         , 'Text'   , { 'td', 'th' }                                                                                                                 ,  },
  { 'sandbox'         , 'Text'   , { 'iframe' }                                                                                                                   ,  },
  { 'spellcheck'      , 'Text'   , true                                                                                                                           ,  },
  { 'scope'           , 'Text'   , { 'th' }                                                                                                                       ,  },
  { 'scoped'          , 'Boolean', { 'style' }                                                                                                                    ,  },
  { 'seamless'        , 'Boolean', { 'iframe' }                                                                                                                   ,  },
  { 'selected'        , 'Boolean', { 'option' }                                                                                                                   ,  },
  { 'shape'           , 'Text'   , { 'area' }                                                                                                                     ,  },
  { 'size'            , 'Text'   , { 'input', 'select' }                                                                                                          ,  },
  { 'sizes'           , 'Text'   , { 'link' }                                                                                                                     ,  },
  { 'sorted'          , 'Text'   , { 'th' }                                                                                                                       ,  },
  { 'span'            , 'Text'   , { 'col', 'colgroup' }                                                                                                          ,  },
  { 'src'             , 'URL'    , { 'audio', 'embed', 'iframe', 'img', 'input', 'script', 'source', 'track', 'video' }                                           ,  },
  { 'srcdoc'          , 'Text'   , { 'iframe' }                                                                                                                   ,  },
  { 'srclang'         , 'Text'   , { 'track' }                                                                                                                    ,  },
  { 'srcset'          , 'Text'   , { 'img' }                                                                                                                      ,  },
  { 'start'           , 'Text'   , { 'ol' }                                                                                                                       ,  },
  { 'step'            , 'Text'   , { 'input' }                                                                                                                    ,  },
  { 'style'           , 'Text'   , true                                                                                                                           ,  },
  { 'tabindex'        , 'Text'   , true                                                                                                                           ,  },
  { 'target'          , 'Text'   , { 'a', 'area', 'base', 'form' }                                                                                                ,  },
  { 'title'           , 'Text'   , true                                                                                                                           ,  },
  { 'translate'       , 'Text'   , true                                                                                                                           ,  },
  { 'type'            , 'Text'   , { 'a', 'area', 'link', 'button', 'embed', 'object', 'script', 'source', 'style', 'input', 'menu', 'menuitem', 'ol' }           ,  },
  { 'typemustmatch'   , 'Boolean', { 'object' }                                                                                                                   ,  },
  { 'usemap'          , 'Text'   , { 'img', 'object' }                                                                                                            ,  },
  { 'value'           , 'Text'   , { 'button', 'option', 'data', 'input', 'li', 'meter', 'progress', 'param' }                                                    ,  },
  { 'width'           , 'Text'   , { 'canvas', 'embed', 'iframe', 'img', 'input', 'object', 'video' }                                                             ,  },
  { 'wrap'            , 'Text'   , { 'textarea' }                                                                                                                 ,  },
  { 'onabort'         , 'Raw'    , true                                                                                                                           ,  },
  { 'onafterprint'    , 'Raw'    , { 'body' }                                                                                                                     ,  },
  { 'onbeforeprint'   , 'Raw'    , { 'body' }                                                                                                                     ,  },
  { 'onbeforeunload'  , 'Raw'    , { 'body' }                                                                                                                     ,  },
  { 'onblur'          , 'Raw'    , true                                                                                                                           ,  },
  { 'oncancel'        , 'Raw'    , true                                                                                                                           ,  },
  { 'oncanplay'       , 'Raw'    , true                                                                                                                           ,  },
  { 'oncanplaythrough', 'Raw'    , true                                                                                                                           ,  },
  { 'onchange'        , 'Raw'    , true                                                                                                                           ,  },
  { 'onclick'         , 'Raw'    , true                                                                                                                           ,  },
  { 'onclose'         , 'Raw'    , true                                                                                                                           ,  },
  { 'oncontextmenu'   , 'Raw'    , true                                                                                                                           ,  },
  { 'oncuechange'     , 'Raw'    , true                                                                                                                           ,  },
  { 'ondblclick'      , 'Raw'    , true                                                                                                                           ,  },
  { 'ondrag'          , 'Raw'    , true                                                                                                                           ,  },
  { 'ondragend'       , 'Raw'    , true                                                                                                                           ,  },
  { 'ondragenter'     , 'Raw'    , true                                                                                                                           ,  },
  { 'ondragexit'      , 'Raw'    , true                                                                                                                           ,  },
  { 'ondragleave'     , 'Raw'    , true                                                                                                                           ,  },
  { 'ondragover'      , 'Raw'    , true                                                                                                                           ,  },
  { 'ondragstart'     , 'Raw'    , true                                                                                                                           ,  },
  { 'ondrop'          , 'Raw'    , true                                                                                                                           ,  },
  { 'ondurationchange', 'Raw'    , true                                                                                                                           ,  },
  { 'onemptied'       , 'Raw'    , true                                                                                                                           ,  },
  { 'onended'         , 'Raw'    , true                                                                                                                           ,  },
  { 'onerror'         , 'Raw'    , true                                                                                                                           ,  },
  { 'onfocus'         , 'Raw'    , true                                                                                                                           ,  },
  { 'onhashchange'    , 'Raw'    , { 'body' }                                                                                                                     ,  },
  { 'oninput'         , 'Raw'    , true                                                                                                                           ,  },
  { 'oninvalid'       , 'Raw'    , true                                                                                                                           ,  },
  { 'onkeydown'       , 'Raw'    , true                                                                                                                           ,  },
  { 'onkeypress'      , 'Raw'    , true                                                                                                                           ,  },
  { 'onkeyup'         , 'Raw'    , true                                                                                                                           ,  },
  { 'onload'          , 'Raw'    , true                                                                                                                           ,  },
  { 'onloadeddata'    , 'Raw'    , true                                                                                                                           ,  },
  { 'onloadedmetadata', 'Raw'    , true                                                                                                                           ,  },
  { 'onloadstart'     , 'Raw'    , true                                                                                                                           ,  },
  { 'onmessage'       , 'Raw'    , { 'body' }                                                                                                                     ,  },
  { 'onmousedown'     , 'Raw'    , true                                                                                                                           ,  },
  { 'onmouseenter'    , 'Raw'    , true                                                                                                                           ,  },
  { 'onmouseleave'    , 'Raw'    , true                                                                                                                           ,  },
  { 'onmousemove'     , 'Raw'    , true                                                                                                                           ,  },
  { 'onmouseout'      , 'Raw'    , true                                                                                                                           ,  },
  { 'onmouseover'     , 'Raw'    , true                                                                                                                           ,  },
  { 'onmouseup'       , 'Raw'    , true                                                                                                                           ,  },
  { 'onmousewheel'    , 'Raw'    , true                                                                                                                           ,  },
  { 'onoffline'       , 'Raw'    , { 'body' }                                                                                                                     ,  },
  { 'ononline'        , 'Raw'    , { 'body' }                                                                                                                     ,  },
  { 'onpagehide'      , 'Raw'    , { 'body' }                                                                                                                     ,  },
  { 'onpageshow'      , 'Raw'    , { 'body' }                                                                                                                     ,  },
  { 'onpause'         , 'Raw'    , true                                                                                                                           ,  },
  { 'onplay'          , 'Raw'    , true                                                                                                                           ,  },
  { 'onplaying'       , 'Raw'    , true                                                                                                                           ,  },
  { 'onpopstate'      , 'Raw'    , { 'body' }                                                                                                                     ,  },
  { 'onprogress'      , 'Raw'    , true                                                                                                                           ,  },
  { 'onratechange'    , 'Raw'    , true                                                                                                                           ,  },
  { 'onreset'         , 'Raw'    , true                                                                                                                           ,  },
  { 'onresize'        , 'Raw'    , { 'body' }                                                                                                                     ,  },
  { 'onscroll'        , 'Raw'    , true                                                                                                                           ,  },
  { 'onseeked'        , 'Raw'    , true                                                                                                                           ,  },
  { 'onseeking'       , 'Raw'    , true                                                                                                                           ,  },
  { 'onselect'        , 'Raw'    , true                                                                                                                           ,  },
  { 'onshow'          , 'Raw'    , true                                                                                                                           ,  },
  { 'onsort'          , 'Raw'    , true                                                                                                                           ,  },
  { 'onstalled'       , 'Raw'    , true                                                                                                                           ,  },
  { 'onstorage'       , 'Raw'    , { 'body' }                                                                                                                     ,  },
  { 'onsubmit'        , 'Raw'    , true                                                                                                                           ,  },
  { 'onsuspend'       , 'Raw'    , true                                                                                                                           ,  },
  { 'ontimeupdate'    , 'Raw'    , true                                                                                                                           ,  },
  { 'ontoggle'        , 'Raw'    , true                                                                                                                           ,  },
  { 'onunload'        , 'Raw'    , { 'body' }                                                                                                                     ,  },
  { 'onvolumechange'  , 'Raw'    , true                                                                                                                           ,  },
  { 'onwaiting'       , 'Raw'    , true                                                                                                                           ,  },
}
return M
